[book]
authors = ["Francis Du"]
language = "en"
multilingual = false
src = "src"
title = "Koifish"
description = "The Koifish Book."

[output.html]
cname="koifish.trisasnava.org"
default-theme = "ayu"
git-repository-url = "https://GITHUB.com/trisasnava/koifish/tree/master/DOCS/src"

[output.html.playpen]
editable = true
copy-js = true
line-numbers = true