name: mdbook-build

on:
  pull_request:
    branches: [ master ]

jobs:
  mdbook-build:
    name: Mdbook Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: mdbook build docs