name: Rust-Build

on:
  pull_request:
    branches: [ master ]

jobs:
  rust_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
